import { roboto } from "@/fonts";
import { PropsWithChildren, Suspense } from "react";
import "./globals.css";
import "./static.css";
import dynamic from "next/dynamic";
import { cookies } from "next/headers";
import Loading from "./loading";
import Script from "next/script";

export const metadata = {
  title: "ICECREAMMUSIC",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <Script src="https://yookassa.ru/payouts-data/3.1.0/widget.js" />
      <body className={roboto.className}>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
