import { getAuthSession } from "@/actions/auth";
import BreadCrumbs from "@/entities/BreadCrumbs/BreadCrumbs";
import Header from "@/entities/Header/Header";
import Sidebar from "@/entities/Sidebar/Sidebar";
import { open } from "@/fonts";
import { SidebarContextProvider } from "@/providers/SidebarContext";
import AppThemeProvider from "@/providers/ThemeContext";
import classNames from "classnames";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { PropsWithChildren } from "react";
import { Error } from "@/entities/Error";
import style from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CabinetLayout({ children }: PropsWithChildren) {
  const theme = cookies().get("__theme__")?.value || "system";

  const session = await getAuthSession();

  if (!session) {
    return <Error statusCode={401} />;
  }

  return (
    <AppThemeProvider attribute="data-theme" defaultTheme={theme}>
      <SidebarContextProvider>
        <main className={classNames(style.main, open.className)}>
          <div className={style.row}>
            <Sidebar />
            <div className={style.col}>
              <Header
                userid={session!.id}
                username={session!.name}
                avatar={session!.avatar}
              />
              <div className={style.content}>
                <BreadCrumbs home="Панель управления" />
                {children}
              </div>
            </div>
          </div>
        </main>
      </SidebarContextProvider>
    </AppThemeProvider>
  );
}
